# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"prepare_data": "00_core.ipynb",
         "pred_data": "00_core.ipynb",
         "BaseExplainer": "00_core.ipynb",
         "KernelExplainer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://muellerzr.github.io/fastshap/"

git_url = "https://github.com/muellerzr/fastshap/tree/master/"

def custom_doc_links(name): return None
