# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ShapInterpretation": "01_interpret.ipynb"}

modules = ["core.py",
           "interp.py"]

doc_url = "https://muellerzr.github.io/fastshap/"

git_url = "https://github.com/muellerzr/fastshap/tree/master/"

def custom_doc_links(name): return None
